<script>
	import IonIcon from '$lib/icon/IonIcon.svelte';
	import SvgIcon from '$lib/icon/SvgIcon.svelte';

	import PageContainer from '$lib/components/PageContainer/PageContainer.svelte';
</script>

<PageContainer>
	<div class="space-y-5 flex-1 overflow-auto icon-container">
		<h1 class="h1">Icon</h1>

		<span> SVG 图标 </span>
		<div class="grid grid-cols-12 gap-4 w-full">
			<div><SvgIcon name="svelte" /></div>
		</div>

		<span> IonIcon图标 </span>
		<div class="grid grid-cols-12 gap-4 w-full">
			<div><IonIcon name="at-outline" strokeWidth={16} color="blue" /></div>
			<div><ion-icon name="heart-outline" /></div>
			<div><ion-icon name="heart-sharp" /></div>
		</div>

		<span> ion-icon 图标 </span>
		<div class="grid grid-cols-12 gap-4 w-full">
			<ion-icon name="accessibility-outline" /><ion-icon
				name="add-outline"
				size="large"
			/><ion-icon name="add-circle-outline" /><ion-icon
				name="airplane-outline"
				size="large"
			/><ion-icon name="alarm-outline" /><ion-icon
				name="albums-outline"
				size="large"
			/><ion-icon name="alert-outline" /><ion-icon
				name="alert-circle-outline"
				size="large"
			/><ion-icon name="american-football-outline" /><ion-icon
				name="analytics-outline"
				size="large"
			/><ion-icon name="aperture-outline" /><ion-icon
				name="apps-outline"
				size="large"
			/><ion-icon name="archive-outline" /><ion-icon
				name="arrow-back-outline"
				size="large"
			/><ion-icon name="arrow-back-circle-outline" /><ion-icon
				name="arrow-down-outline"
				size="large"
			/><ion-icon name="arrow-down-circle-outline" /><ion-icon
				name="arrow-forward-outline"
				size="large"
			/><ion-icon name="arrow-forward-circle-outline" /><ion-icon
				name="arrow-redo-outline"
				size="large"
			/><ion-icon name="arrow-redo-circle-outline" /><ion-icon
				name="arrow-undo-outline"
				size="large"
			/><ion-icon name="arrow-undo-circle-outline" /><ion-icon
				name="arrow-up-outline"
				size="large"
			/><ion-icon name="arrow-up-circle-outline" /><ion-icon
				name="at-outline"
				size="large"
			/><ion-icon name="at-circle-outline" /><ion-icon
				name="attach-outline"
				size="large"
			/><ion-icon name="backspace-outline" /><ion-icon
				name="bag-outline"
				size="large"
			/><ion-icon name="bag-add-outline" /><ion-icon
				name="bag-check-outline"
				size="large"
			/><ion-icon name="bag-handle-outline" /><ion-icon
				name="bag-remove-outline"
				size="large"
			/><ion-icon name="balloon-outline" /><ion-icon
				name="ban-outline"
				size="large"
			/><ion-icon name="bandage-outline" /><ion-icon
				name="bar-chart-outline"
				size="large"
			/><ion-icon name="barbell-outline" /><ion-icon
				name="barcode-outline"
				size="large"
			/><ion-icon name="baseball-outline" /><ion-icon
				name="basket-outline"
				size="large"
			/><ion-icon name="basketball-outline" /><ion-icon
				name="battery-charging-outline"
				size="large"
			/><ion-icon name="battery-dead-outline" /><ion-icon
				name="battery-full-outline"
				size="large"
			/><ion-icon name="battery-half-outline" /><ion-icon
				name="beaker-outline"
				size="large"
			/><ion-icon name="bed-outline" /><ion-icon
				name="beer-outline"
				size="large"
			/><ion-icon name="bicycle-outline" /><ion-icon
				name="bluetooth-outline"
				size="large"
			/><ion-icon name="boat-outline" /><ion-icon
				name="body-outline"
				size="large"
			/><ion-icon name="bonfire-outline" /><ion-icon
				name="book-outline"
				size="large"
			/><ion-icon name="bookmark-outline" /><ion-icon
				name="bookmarks-outline"
				size="large"
			/><ion-icon name="bowling-ball-outline" /><ion-icon
				name="briefcase-outline"
				size="large"
			/><ion-icon name="browsers-outline" /><ion-icon
				name="brush-outline"
				size="large"
			/><ion-icon name="bug-outline" /><ion-icon
				name="build-outline"
				size="large"
			/><ion-icon name="bulb-outline" /><ion-icon
				name="bus-outline"
				size="large"
			/><ion-icon name="business-outline" /><ion-icon
				name="cafe-outline"
				size="large"
			/><ion-icon name="calculator-outline" /><ion-icon
				name="calendar-outline"
				size="large"
			/><ion-icon name="calendar-clear-outline" /><ion-icon
				name="calendar-number-outline"
				size="large"
			/><ion-icon name="call-outline" /><ion-icon
				name="camera-outline"
				size="large"
			/><ion-icon name="camera-reverse-outline" /><ion-icon
				name="car-outline"
				size="large"
			/><ion-icon name="car-sport-outline" /><ion-icon
				name="card-outline"
				size="large"
			/><ion-icon name="caret-back-outline" /><ion-icon
				name="caret-back-circle-outline"
				size="large"
			/><ion-icon name="caret-down-outline" /><ion-icon
				name="caret-down-circle-outline"
				size="large"
			/><ion-icon name="caret-forward-outline" /><ion-icon
				name="caret-forward-circle-outline"
				size="large"
			/><ion-icon name="caret-up-outline" /><ion-icon
				name="caret-up-circle-outline"
				size="large"
			/><ion-icon name="cart-outline" /><ion-icon
				name="cash-outline"
				size="large"
			/><ion-icon name="cellular-outline" /><ion-icon
				name="chatbox-outline"
				size="large"
			/><ion-icon name="chatbox-ellipses-outline" /><ion-icon
				name="chatbubble-outline"
				size="large"
			/><ion-icon name="chatbubble-ellipses-outline" /><ion-icon
				name="chatbubbles-outline"
				size="large"
			/><ion-icon name="checkbox-outline" /><ion-icon
				name="checkmark-outline"
				size="large"
			/><ion-icon name="checkmark-circle-outline" /><ion-icon
				name="checkmark-done-outline"
				size="large"
			/><ion-icon name="checkmark-done-circle-outline" /><ion-icon
				name="chevron-back-outline"
				size="large"
			/><ion-icon name="chevron-back-circle-outline" /><ion-icon
				name="chevron-collapse-outline"
				size="large"
			/><ion-icon name="chevron-down-outline" /><ion-icon
				name="chevron-down-circle-outline"
				size="large"
			/><ion-icon name="chevron-expand-outline" /><ion-icon
				name="chevron-forward-outline"
				size="large"
			/><ion-icon name="chevron-forward-circle-outline" /><ion-icon
				name="chevron-up-outline"
				size="large"
			/><ion-icon name="chevron-up-circle-outline" /><ion-icon
				name="clipboard-outline"
				size="large"
			/><ion-icon name="close-outline" /><ion-icon
				name="close-circle-outline"
				size="large"
			/><ion-icon name="cloud-outline" /><ion-icon
				name="cloud-circle-outline"
				size="large"
			/><ion-icon name="cloud-done-outline" /><ion-icon
				name="cloud-download-outline"
				size="large"
			/><ion-icon name="cloud-offline-outline" /><ion-icon
				name="cloud-upload-outline"
				size="large"
			/><ion-icon name="cloudy-outline" /><ion-icon
				name="cloudy-night-outline"
				size="large"
			/><ion-icon name="code-outline" /><ion-icon
				name="code-download-outline"
				size="large"
			/><ion-icon name="code-slash-outline" /><ion-icon
				name="code-working-outline"
				size="large"
			/><ion-icon name="cog-outline" /><ion-icon
				name="color-fill-outline"
				size="large"
			/><ion-icon name="color-filter-outline" /><ion-icon
				name="color-palette-outline"
				size="large"
			/><ion-icon name="color-wand-outline" /><ion-icon
				name="compass-outline"
				size="large"
			/><ion-icon name="construct-outline" /><ion-icon
				name="contract-outline"
				size="large"
			/><ion-icon name="contrast-outline" /><ion-icon
				name="copy-outline"
				size="large"
			/><ion-icon name="create-outline" /><ion-icon
				name="crop-outline"
				size="large"
			/><ion-icon name="cube-outline" /><ion-icon
				name="cut-outline"
				size="large"
			/><ion-icon name="desktop-outline" /><ion-icon
				name="diamond-outline"
				size="large"
			/><ion-icon name="dice-outline" /><ion-icon
				name="disc-outline"
				size="large"
			/><ion-icon name="document-outline" /><ion-icon
				name="document-attach-outline"
				size="large"
			/><ion-icon name="document-lock-outline" /><ion-icon
				name="document-text-outline"
				size="large"
			/><ion-icon name="documents-outline" /><ion-icon
				name="download-outline"
				size="large"
			/><ion-icon name="duplicate-outline" /><ion-icon
				name="ear-outline"
				size="large"
			/><ion-icon name="earth-outline" /><ion-icon
				name="easel-outline"
				size="large"
			/><ion-icon name="egg-outline" /><ion-icon
				name="ellipse-outline"
				size="large"
			/><ion-icon name="ellipsis-horizontal-outline" /><ion-icon
				name="ellipsis-horizontal-circle-outline"
				size="large"
			/><ion-icon name="ellipsis-vertical-outline" /><ion-icon
				name="ellipsis-vertical-circle-outline"
				size="large"
			/><ion-icon name="enter-outline" /><ion-icon
				name="exit-outline"
				size="large"
			/><ion-icon name="expand-outline" /><ion-icon
				name="extension-puzzle-outline"
				size="large"
			/><ion-icon name="eye-outline" /><ion-icon
				name="eye-off-outline"
				size="large"
			/><ion-icon name="eyedrop-outline" /><ion-icon
				name="fast-food-outline"
				size="large"
			/><ion-icon name="female-outline" /><ion-icon
				name="file-tray-outline"
				size="large"
			/><ion-icon name="file-tray-full-outline" /><ion-icon
				name="file-tray-stacked-outline"
				size="large"
			/><ion-icon name="film-outline" /><ion-icon
				name="filter-outline"
				size="large"
			/><ion-icon name="filter-circle-outline" /><ion-icon
				name="finger-print-outline"
				size="large"
			/><ion-icon name="fish-outline" /><ion-icon
				name="fitness-outline"
				size="large"
			/><ion-icon name="flag-outline" /><ion-icon
				name="flame-outline"
				size="large"
			/><ion-icon name="flash-outline" /><ion-icon
				name="flash-off-outline"
				size="large"
			/><ion-icon name="flashlight-outline" /><ion-icon
				name="flask-outline"
				size="large"
			/><ion-icon name="flower-outline" /><ion-icon
				name="folder-outline"
				size="large"
			/><ion-icon name="folder-open-outline" /><ion-icon
				name="football-outline"
				size="large"
			/><ion-icon name="footsteps-outline" /><ion-icon
				name="funnel-outline"
				size="large"
			/><ion-icon name="game-controller-outline" /><ion-icon
				name="gift-outline"
				size="large"
			/><ion-icon name="git-branch-outline" /><ion-icon
				name="git-commit-outline"
				size="large"
			/><ion-icon name="git-compare-outline" /><ion-icon
				name="git-merge-outline"
				size="large"
			/><ion-icon name="git-network-outline" /><ion-icon
				name="git-pull-request-outline"
				size="large"
			/><ion-icon name="glasses-outline" /><ion-icon
				name="globe-outline"
				size="large"
			/><ion-icon name="golf-outline" /><ion-icon
				name="grid-outline"
				size="large"
			/><ion-icon name="hammer-outline" /><ion-icon
				name="hand-left-outline"
				size="large"
			/><ion-icon name="hand-right-outline" /><ion-icon
				name="happy-outline"
				size="large"
			/><ion-icon name="hardware-chip-outline" /><ion-icon
				name="headset-outline"
				size="large"
			/><ion-icon name="heart-outline" /><ion-icon
				name="heart-circle-outline"
				size="large"
			/><ion-icon name="heart-dislike-outline" /><ion-icon
				name="heart-dislike-circle-outline"
				size="large"
			/><ion-icon name="heart-half-outline" /><ion-icon
				name="help-outline"
				size="large"
			/><ion-icon name="help-buoy-outline" /><ion-icon
				name="help-circle-outline"
				size="large"
			/><ion-icon name="home-outline" /><ion-icon
				name="hourglass-outline"
				size="large"
			/><ion-icon name="ice-cream-outline" /><ion-icon
				name="id-card-outline"
				size="large"
			/><ion-icon name="image-outline" /><ion-icon
				name="images-outline"
				size="large"
			/><ion-icon name="infinite-outline" /><ion-icon
				name="information-outline"
				size="large"
			/><ion-icon name="information-circle-outline" /><ion-icon
				name="invert-mode-outline"
				size="large"
			/><ion-icon name="journal-outline" /><ion-icon
				name="key-outline"
				size="large"
			/><ion-icon name="keypad-outline" /><ion-icon
				name="language-outline"
				size="large"
			/><ion-icon name="laptop-outline" /><ion-icon
				name="layers-outline"
				size="large"
			/><ion-icon name="leaf-outline" /><ion-icon
				name="library-outline"
				size="large"
			/><ion-icon name="link-outline" /><ion-icon
				name="list-outline"
				size="large"
			/><ion-icon name="list-circle-outline" /><ion-icon
				name="locate-outline"
				size="large"
			/><ion-icon name="location-outline" /><ion-icon
				name="lock-closed-outline"
				size="large"
			/><ion-icon name="lock-open-outline" /><ion-icon
				name="log-in-outline"
				size="large"
			/><ion-icon name="log-out-outline" /><ion-icon
				name="magnet-outline"
				size="large"
			/><ion-icon name="mail-outline" /><ion-icon
				name="mail-open-outline"
				size="large"
			/><ion-icon name="mail-unread-outline" /><ion-icon
				name="male-outline"
				size="large"
			/><ion-icon name="male-female-outline" /><ion-icon
				name="man-outline"
				size="large"
			/><ion-icon name="map-outline" /><ion-icon
				name="medal-outline"
				size="large"
			/><ion-icon name="medical-outline" /><ion-icon
				name="medkit-outline"
				size="large"
			/><ion-icon name="megaphone-outline" /><ion-icon
				name="menu-outline"
				size="large"
			/><ion-icon name="mic-outline" /><ion-icon
				name="mic-circle-outline"
				size="large"
			/><ion-icon name="mic-off-outline" /><ion-icon
				name="mic-off-circle-outline"
				size="large"
			/><ion-icon name="moon-outline" /><ion-icon
				name="move-outline"
				size="large"
			/><ion-icon name="musical-note-outline" /><ion-icon
				name="musical-notes-outline"
				size="large"
			/><ion-icon name="navigate-outline" /><ion-icon
				name="navigate-circle-outline"
				size="large"
			/><ion-icon name="newspaper-outline" /><ion-icon
				name="notifications-outline"
				size="large"
			/><ion-icon name="notifications-circle-outline" /><ion-icon
				name="notifications-off-outline"
				size="large"
			/><ion-icon name="notifications-off-circle-outline" /><ion-icon
				name="nuclear-outline"
				size="large"
			/><ion-icon name="nutrition-outline" /><ion-icon
				name="open-outline"
				size="large"
			/><ion-icon name="options-outline" /><ion-icon
				name="paper-plane-outline"
				size="large"
			/><ion-icon name="partly-sunny-outline" /><ion-icon
				name="pause-outline"
				size="large"
			/><ion-icon name="pause-circle-outline" /><ion-icon
				name="paw-outline"
				size="large"
			/><ion-icon name="pencil-outline" /><ion-icon
				name="people-outline"
				size="large"
			/><ion-icon name="people-circle-outline" /><ion-icon
				name="person-outline"
				size="large"
			/><ion-icon name="person-add-outline" /><ion-icon
				name="person-circle-outline"
				size="large"
			/><ion-icon name="person-remove-outline" /><ion-icon
				name="phone-landscape-outline"
				size="large"
			/><ion-icon name="phone-portrait-outline" /><ion-icon
				name="pie-chart-outline"
				size="large"
			/><ion-icon name="pin-outline" /><ion-icon
				name="pint-outline"
				size="large"
			/><ion-icon name="pizza-outline" /><ion-icon
				name="planet-outline"
				size="large"
			/><ion-icon name="play-outline" /><ion-icon
				name="play-back-outline"
				size="large"
			/><ion-icon name="play-back-circle-outline" /><ion-icon
				name="play-circle-outline"
				size="large"
			/><ion-icon name="play-forward-outline" /><ion-icon
				name="play-forward-circle-outline"
				size="large"
			/><ion-icon name="play-skip-back-outline" /><ion-icon
				name="play-skip-back-circle-outline"
				size="large"
			/><ion-icon name="play-skip-forward-outline" /><ion-icon
				name="play-skip-forward-circle-outline"
				size="large"
			/><ion-icon name="podium-outline" /><ion-icon
				name="power-outline"
				size="large"
			/><ion-icon name="pricetag-outline" /><ion-icon
				name="pricetags-outline"
				size="large"
			/><ion-icon name="print-outline" /><ion-icon
				name="prism-outline"
				size="large"
			/><ion-icon name="pulse-outline" /><ion-icon
				name="push-outline"
				size="large"
			/><ion-icon name="qr-code-outline" /><ion-icon
				name="radio-outline"
				size="large"
			/><ion-icon name="radio-button-off-outline" /><ion-icon
				name="radio-button-on-outline"
				size="large"
			/><ion-icon name="rainy-outline" /><ion-icon
				name="reader-outline"
				size="large"
			/><ion-icon name="receipt-outline" /><ion-icon
				name="recording-outline"
				size="large"
			/><ion-icon name="refresh-outline" /><ion-icon
				name="refresh-circle-outline"
				size="large"
			/><ion-icon name="reload-outline" /><ion-icon
				name="reload-circle-outline"
				size="large"
			/><ion-icon name="remove-outline" /><ion-icon
				name="remove-circle-outline"
				size="large"
			/><ion-icon name="reorder-four-outline" /><ion-icon
				name="reorder-three-outline"
				size="large"
			/><ion-icon name="reorder-two-outline" /><ion-icon
				name="repeat-outline"
				size="large"
			/><ion-icon name="resize-outline" /><ion-icon
				name="restaurant-outline"
				size="large"
			/><ion-icon name="return-down-back-outline" /><ion-icon
				name="return-down-forward-outline"
				size="large"
			/><ion-icon name="return-up-back-outline" /><ion-icon
				name="return-up-forward-outline"
				size="large"
			/><ion-icon name="ribbon-outline" /><ion-icon
				name="rocket-outline"
				size="large"
			/><ion-icon name="rose-outline" /><ion-icon
				name="sad-outline"
				size="large"
			/><ion-icon name="save-outline" /><ion-icon
				name="scale-outline"
				size="large"
			/><ion-icon name="scan-outline" /><ion-icon
				name="scan-circle-outline"
				size="large"
			/><ion-icon name="school-outline" /><ion-icon
				name="search-outline"
				size="large"
			/><ion-icon name="search-circle-outline" /><ion-icon
				name="send-outline"
				size="large"
			/><ion-icon name="server-outline" /><ion-icon
				name="settings-outline"
				size="large"
			/><ion-icon name="shapes-outline" /><ion-icon
				name="share-outline"
				size="large"
			/><ion-icon name="share-social-outline" /><ion-icon
				name="shield-outline"
				size="large"
			/><ion-icon name="shield-checkmark-outline" /><ion-icon
				name="shield-half-outline"
				size="large"
			/><ion-icon name="shirt-outline" /><ion-icon
				name="shuffle-outline"
				size="large"
			/><ion-icon name="skull-outline" /><ion-icon
				name="snow-outline"
				size="large"
			/><ion-icon name="sparkles-outline" /><ion-icon
				name="speedometer-outline"
				size="large"
			/><ion-icon name="square-outline" /><ion-icon
				name="star-outline"
				size="large"
			/><ion-icon name="star-half-outline" /><ion-icon
				name="stats-chart-outline"
				size="large"
			/><ion-icon name="stop-outline" /><ion-icon
				name="stop-circle-outline"
				size="large"
			/><ion-icon name="stopwatch-outline" /><ion-icon
				name="storefront-outline"
				size="large"
			/><ion-icon name="subway-outline" /><ion-icon
				name="sunny-outline"
				size="large"
			/><ion-icon name="swap-horizontal-outline" /><ion-icon
				name="swap-vertical-outline"
				size="large"
			/><ion-icon name="sync-outline" /><ion-icon
				name="sync-circle-outline"
				size="large"
			/><ion-icon name="tablet-landscape-outline" /><ion-icon
				name="tablet-portrait-outline"
				size="large"
			/><ion-icon name="telescope-outline" /><ion-icon
				name="tennisball-outline"
				size="large"
			/><ion-icon name="terminal-outline" /><ion-icon
				name="text-outline"
				size="large"
			/><ion-icon name="thermometer-outline" /><ion-icon
				name="thumbs-down-outline"
				size="large"
			/><ion-icon name="thumbs-up-outline" /><ion-icon
				name="thunderstorm-outline"
				size="large"
			/><ion-icon name="ticket-outline" /><ion-icon
				name="time-outline"
				size="large"
			/><ion-icon name="timer-outline" /><ion-icon
				name="today-outline"
				size="large"
			/><ion-icon name="toggle-outline" /><ion-icon
				name="trail-sign-outline"
				size="large"
			/><ion-icon name="train-outline" /><ion-icon
				name="transgender-outline"
				size="large"
			/><ion-icon name="trash-outline" /><ion-icon
				name="trash-bin-outline"
				size="large"
			/><ion-icon name="trending-down-outline" /><ion-icon
				name="trending-up-outline"
				size="large"
			/><ion-icon name="triangle-outline" /><ion-icon
				name="trophy-outline"
				size="large"
			/><ion-icon name="tv-outline" /><ion-icon
				name="umbrella-outline"
				size="large"
			/><ion-icon name="unlink-outline" /><ion-icon
				name="videocam-outline"
				size="large"
			/><ion-icon name="videocam-off-outline" /><ion-icon
				name="volume-high-outline"
				size="large"
			/><ion-icon name="volume-low-outline" /><ion-icon
				name="volume-medium-outline"
				size="large"
			/><ion-icon name="volume-mute-outline" /><ion-icon
				name="volume-off-outline"
				size="large"
			/><ion-icon name="walk-outline" /><ion-icon
				name="wallet-outline"
				size="large"
			/><ion-icon name="warning-outline" /><ion-icon
				name="watch-outline"
				size="large"
			/><ion-icon name="water-outline" /><ion-icon
				name="wifi-outline"
				size="large"
			/><ion-icon name="wine-outline" /><ion-icon name="woman-outline" />
		</div>
	</div>
</PageContainer>

<style lang="postcss">
	ion-icon {
		visibility: visible;
	}
	.icon-container span{
		@apply my-4 font-bold border-b-2 border-spacing-2;
	}
</style>
